import { z } from "zod";
import { DEMO_VEHICLES } from "@/features/shared/lib/demo-workspace";

import {
  optionalNumber,
  optionalText,
  requiredNumber,
  requiredText,
} from "@/features/shared/schemas/schema-helpers";
import type { ResourceDefinition } from "@/features/shared/types/resource";

export const vehicleDefinition: ResourceDefinition = {
  key: "vehicle",
  // Reads add each car's service status; writes go to `vehicles`.
  table: "vehicle_list",
  singular: "Vehicle",
  plural: "Vehicles",
  route: "/vehicles",
  titleField: "plate_number",
  subtitleField: "name",
  searchColumn: "plate_number",
  description:
    "Register fleet vehicles, maintain availability, and open location or rental history.",
  writeRoles: ["owner", "admin"],
  archive: { field: "status", value: "inactive", label: "Archive vehicle" },
  filters: [
    {
      param: "service",
      column: "service_status",
      op: "eq",
      label: "Service",
      picker: true,
      valueLabels: {
        overdue: "Overdue",
        due_soon: "Due soon",
        on_schedule: "On schedule",
        no_schedule: "No schedule",
      },
    },
  ],
  detailColumns: [
    "id",
    "plate_number",
    "name",
    "make",
    "model",
    "year",
    "color",
    "category",
    "transmission",
    "fuel_type",
    "seating_capacity",
    "daily_rate",
    "half_day_rate",
    "hourly_rate",
    "current_odometer",
    "status",
    "photo_url",
    "showcase_image_url",
    "notes",
  ],
  schema: z.object({
    plate_number: requiredText("Plate number", 32),
    name: requiredText("Vehicle name", 120),
    make: requiredText("Make", 80),
    model: requiredText("Model", 80),
    year: requiredNumber("Year", 1900).max(2100),
    color: optionalText(60),
    category: optionalText(80),
    transmission: z.enum(["automatic", "manual", "cvt"]).optional(),
    fuel_type: z
      .enum(["gasoline", "diesel", "hybrid", "electric", "other"])
      .optional(),
    seating_capacity: optionalNumber(1),
    daily_rate: requiredNumber("Daily rate", 1),
    half_day_rate: optionalNumber(1),
    hourly_rate: optionalNumber(1),
    current_odometer: optionalNumber(0),
    status: z.enum(["available", "maintenance", "inactive"]),
    notes: optionalText(),
  }),
  fields: [
    {
      name: "plate_number",
      label: "Plate number",
      required: true,
      placeholder: "ABC 1234",
    },
    {
      name: "name",
      label: "Vehicle name",
      required: true,
      placeholder: "Toyota Vios 01",
    },
    { name: "make", label: "Make", required: true },
    { name: "model", label: "Model", required: true },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "color", label: "Color" },
    { name: "category", label: "Category", placeholder: "Sedan" },
    {
      name: "transmission",
      label: "Transmission",
      type: "select",
      options: [
        { value: "automatic", label: "Automatic" },
        { value: "manual", label: "Manual" },
        { value: "cvt", label: "CVT" },
      ],
    },
    {
      name: "fuel_type",
      label: "Fuel type",
      type: "select",
      options: [
        { value: "gasoline", label: "Gasoline" },
        { value: "diesel", label: "Diesel" },
        { value: "hybrid", label: "Hybrid" },
        { value: "electric", label: "Electric" },
        { value: "other", label: "Other" },
      ],
    },
    { name: "seating_capacity", label: "Seating capacity", type: "number" },
    {
      name: "daily_rate",
      label: "Daily rate (PHP)",
      type: "number",
      required: true,
      placeholder: "2000",
      step: "1",
      description:
        "Price per 24 hours. Rate changes are blocked while this car has an active or reserved booking.",
    },
    {
      name: "half_day_rate",
      label: "12-hour rate (PHP)",
      type: "number",
      placeholder: "1200",
      step: "1",
      description:
        "Charged when the leftover hours past the whole days are 12 or fewer and it is cheaper than hourly. Leave blank to skip.",
    },
    {
      name: "hourly_rate",
      label: "Hourly rate (PHP)",
      type: "number",
      placeholder: "150",
      step: "1",
      description:
        "Charged per leftover hour. Leftover hours never cost more than one day. Leave blank to skip.",
    },
    {
      name: "current_odometer",
      label: "Current odometer (km)",
      type: "number",
      step: "0.1",
    },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      description:
        "Operational status only. Reservations come from booking dates, not this field. An available car can be rented from here right away; it shows on the website once all 6 gallery photos are uploaded.",
      options: ["available", "maintenance", "inactive"].map((value) => ({
        value,
        label: value.replaceAll("_", " "),
      })),
    },
    {
      name: "photo",
      label: "Cover photo (optional)",
      type: "image",
      description:
        "Optional shortcut for the front gallery slot. Prefer the Photo gallery tab — all 6 angles are needed before the car shows on the website.",
      removable: true,
      removeNote:
        "This also removes the Front gallery photo, which takes the car off the website until a new one is added.",
      className: "md:col-span-2",
    },
    {
      name: "showcase_image",
      label: "Landing page image (optional)",
      type: "image",
      accept: "image/png,image/webp",
      previewColumn: "showcase_image_url",
      removable: true,
      removeNote: "The car leaves the homepage hero.",
      description:
        "Front view of the car with a transparent background (PNG or WebP, up to 5MB). Available cars with this image appear in the homepage hero, where customers flip through them.",
      className: "md:col-span-2",
    },
    {
      name: "notes",
      label: "Notes",
      type: "textarea",
      className: "md:col-span-2",
    },
  ],
  columns: [
    { key: "photo_url", label: "Photo", format: "image" },
    { key: "plate_number", label: "Plate" },
    { key: "name", label: "Vehicle" },
    { key: "category", label: "Category" },
    { key: "daily_rate", label: "Daily rate", format: "number" },
    { key: "status", label: "Status", format: "status" },
    { key: "service_status", label: "Service", format: "status" },
    { key: "updated_at", label: "Last updated", format: "datetime" },
  ],
  demoRows: DEMO_VEHICLES.map((vehicle) => ({
    id: vehicle.id,
    plate_number: vehicle.plateNumber,
    name: vehicle.name,
    category: vehicle.category,
    daily_rate: vehicle.dailyRate,
    status: vehicle.status,
    service_status: "no_schedule",
    photo_url: null,
    updated_at: vehicle.createdAt,
  })),
};
