import { z } from "zod";

import {
  optionalNumber,
  optionalText,
  requiredNumber,
  requiredText,
} from "@/features/shared/schemas/schema-helpers";
import type { ResourceDefinition } from "@/features/shared/types/resource";

export const vehicleDefinition: ResourceDefinition = {
  key: "vehicle",
  table: "vehicles",
  singular: "Vehicle",
  plural: "Vehicles",
  route: "/vehicles",
  titleField: "plate_number",
  subtitleField: "name",
  searchColumn: "plate_number",
  description:
    "Register fleet vehicles, maintain availability, and open location or rental history.",
  writeRoles: ["owner", "admin"],
  archive: { field: "status", value: "inactive", label: "Archive vehicle" },
  detailColumns: [
    "id",
    "plate_number",
    "name",
    "make",
    "model",
    "year",
    "color",
    "category",
    "transmission",
    "fuel_type",
    "seating_capacity",
    "daily_rate",
    "current_odometer",
    "status",
    "photo_url",
    "notes",
  ],
  schema: z.object({
    plate_number: requiredText("Plate number", 32),
    name: requiredText("Vehicle name", 120),
    make: requiredText("Make", 80),
    model: requiredText("Model", 80),
    year: requiredNumber("Year", 1900).max(2100),
    color: optionalText(60),
    category: optionalText(80),
    transmission: z.enum(["automatic", "manual", "cvt"]).optional(),
    fuel_type: z
      .enum(["gasoline", "diesel", "hybrid", "electric", "other"])
      .optional(),
    seating_capacity: optionalNumber(1),
    daily_rate: requiredNumber("Daily rate", 1),
    current_odometer: optionalNumber(0),
    status: z.enum(["available", "maintenance", "inactive"]),
    notes: optionalText(),
  }),
  fields: [
    {
      name: "plate_number",
      label: "Plate number",
      required: true,
      placeholder: "ABC 1234",
    },
    {
      name: "name",
      label: "Vehicle name",
      required: true,
      placeholder: "Toyota Vios 01",
    },
    { name: "make", label: "Make", required: true },
    { name: "model", label: "Model", required: true },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "color", label: "Color" },
    { name: "category", label: "Category", placeholder: "Sedan" },
    {
      name: "transmission",
      label: "Transmission",
      type: "select",
      options: [
        { value: "automatic", label: "Automatic" },
        { value: "manual", label: "Manual" },
        { value: "cvt", label: "CVT" },
      ],
    },
    {
      name: "fuel_type",
      label: "Fuel type",
      type: "select",
      options: [
        { value: "gasoline", label: "Gasoline" },
        { value: "diesel", label: "Diesel" },
        { value: "hybrid", label: "Hybrid" },
        { value: "electric", label: "Electric" },
        { value: "other", label: "Other" },
      ],
    },
    { name: "seating_capacity", label: "Seating capacity", type: "number" },
    {
      name: "daily_rate",
      label: "Daily rate (PHP)",
      type: "number",
      required: true,
      placeholder: "2000",
      step: "1",
      description:
        "Rate changes are blocked while this car has an active or reserved booking.",
    },
    {
      name: "current_odometer",
      label: "Current odometer (km)",
      type: "number",
      step: "0.1",
    },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      description:
        "Operational status only. Reservations come from booking dates, not this field. Available requires all 6 gallery photos.",
      options: ["available", "maintenance", "inactive"].map((value) => ({
        value,
        label: value.replaceAll("_", " "),
      })),
    },
    {
      name: "photo",
      label: "Cover photo (optional)",
      type: "image",
      description:
        "Optional shortcut for the front gallery slot. Prefer the Photo gallery tab — all 6 angles are required before Available.",
      className: "md:col-span-2",
    },
    {
      name: "notes",
      label: "Notes",
      type: "textarea",
      className: "md:col-span-2",
    },
  ],
  columns: [
    { key: "photo_url", label: "Photo", format: "image" },
    { key: "plate_number", label: "Plate" },
    { key: "name", label: "Vehicle" },
    { key: "category", label: "Category" },
    { key: "daily_rate", label: "Daily rate", format: "number" },
    { key: "status", label: "Status", format: "status" },
    { key: "updated_at", label: "Last updated", format: "datetime" },
  ],
  demoRows: [
    {
      id: "demo-vehicle",
      plate_number: "NCR 1842",
      name: "Toyota Vios 01",
      category: "Sedan",
      daily_rate: 2000,
      status: "available",
      photo_url: null,
      updated_at: "2026-07-15T01:12:00Z",
    },
  ],
};
