import { z } from "zod";
import {
  optionalNumber,
  optionalText,
  requiredText,
} from "@/features/shared/schemas/schema-helpers";
import type { ResourceDefinition } from "@/features/shared/types/resource";

const optionalGeoJson = z
  .string()
  .trim()
  .max(10_000)
  .optional()
  .refine((value) => {
    if (!value) return true;
    try {
      const parsed = JSON.parse(value);
      return typeof parsed === "object" && parsed !== null;
    } catch {
      return false;
    }
  }, "Enter valid GeoJSON.")
  .transform((value) => (value ? JSON.parse(value) : undefined));

export const geofenceDefinition: ResourceDefinition = {
  key: "geofence",
  table: "geofences",
  singular: "Geofence",
  plural: "Geofences",
  route: "/geofences",
  titleField: "name",
  subtitleField: "geofence_type",
  searchColumn: "name",
  description:
    "Define allowed, restricted, branch, pickup, and return areas for fleet alerts.",
  writeRoles: ["owner", "admin"],
  archive: { field: "is_active", value: false, label: "Disable geofence" },
  schema: z
    .object({
      name: requiredText("Name", 120),
      description: optionalText(500),
      shape_type: z.enum(["circle", "polygon"]),
      center_latitude: optionalNumber(-90).pipe(z.number().max(90).optional()),
      center_longitude: optionalNumber(-180).pipe(
        z.number().max(180).optional(),
      ),
      radius_meters: optionalNumber(1),
      geometry_geojson: optionalGeoJson,
      geofence_type: z.enum([
        "allowed_area",
        "restricted_area",
        "branch",
        "pickup_zone",
        "return_zone",
      ]),
      alert_mode: z.enum(["entry", "exit", "both"]),
      is_active: z.boolean(),
    })
    .superRefine((value, context) => {
      if (
        value.shape_type === "circle" &&
        (value.center_latitude === undefined ||
          value.center_longitude === undefined ||
          value.radius_meters === undefined)
      ) {
        context.addIssue({
          code: "custom",
          path: ["radius_meters"],
          message: "Circle geofences require a center and radius.",
        });
      }
      if (value.shape_type === "polygon" && !value.geometry_geojson) {
        context.addIssue({
          code: "custom",
          path: ["geometry_geojson"],
          message: "Polygon geofences require GeoJSON geometry.",
        });
      }
    }),
  fields: [
    { name: "name", label: "Name", required: true },
    { name: "description", label: "Description" },
    {
      name: "shape_type",
      label: "Shape",
      type: "select",
      required: true,
      options: [
        { value: "circle", label: "Circle" },
        { value: "polygon", label: "Polygon" },
      ],
    },
    {
      name: "geofence_type",
      label: "Geofence type",
      type: "select",
      required: true,
      options: [
        "allowed_area",
        "restricted_area",
        "branch",
        "pickup_zone",
        "return_zone",
      ].map((value) => ({ value, label: value.replaceAll("_", " ") })),
    },
    {
      name: "center_latitude",
      label: "Center latitude",
      type: "number",
      step: "any",
    },
    {
      name: "center_longitude",
      label: "Center longitude",
      type: "number",
      step: "any",
    },
    {
      name: "radius_meters",
      label: "Radius (meters)",
      type: "number",
      step: "0.1",
    },
    {
      name: "alert_mode",
      label: "Alert on",
      type: "select",
      required: true,
      options: ["entry", "exit", "both"].map((value) => ({
        value,
        label: value,
      })),
    },
    {
      name: "geometry_geojson",
      label: "Polygon GeoJSON",
      type: "textarea",
      description:
        "For polygon shapes, paste a valid GeoJSON geometry generated by the map editor.",
      className: "md:col-span-2",
    },
    { name: "is_active", label: "Geofence is active", type: "checkbox" },
  ],
  columns: [
    { key: "name", label: "Geofence" },
    { key: "geofence_type", label: "Type", format: "status" },
    { key: "shape_type", label: "Shape" },
    { key: "alert_mode", label: "Alert mode" },
    { key: "is_active", label: "Active", format: "boolean" },
  ],
  demoRows: [
    {
      id: "demo-geofence",
      name: "Metro Manila allowed area",
      geofence_type: "allowed_area",
      shape_type: "circle",
      alert_mode: "exit",
      is_active: true,
    },
  ],
};
